import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
const hash = createHash("sha256");
async function visit(path) {
  const entries = await readdir(path, { withFileTypes: true });
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const file = `${path}/${entry.name}`;
    if (file === "src/build-version.ts") continue;
    if (entry.isDirectory()) await visit(file);
    else {
      hash.update(file);
      hash.update(await readFile(file));
    }
  }
}
for (const folder of ["src", "content", "scripts"]) await visit(folder);
for (const file of [
  "index.html",
  "package.json",
  "pnpm-lock.yaml",
  "vite.config.ts",
]) {
  hash.update(file);
  hash.update(await readFile(file));
}
await writeFile(
  "src/build-version.ts",
  `// Generated by scripts/build-version.mjs.\nexport const BUILD_VERSION = "${hash.digest("hex").slice(0, 16)}";\n`,
);
