// Generated by scripts/prepare-game-assets.mjs.
export const itemAssets = {
  ammo_electric_chain: new URL(
    "./items/ammo/runtime/ammo_electric_chain.webp",
    import.meta.url,
  ).href,
  ammo_fiery: new URL("./items/ammo/runtime/ammo_fiery.webp", import.meta.url)
    .href,
  ammo_frost: new URL("./items/ammo/runtime/ammo_frost.webp", import.meta.url)
    .href,
  ammo_legendary_omni: new URL(
    "./items/ammo/runtime/ammo_legendary_omni.webp",
    import.meta.url,
  ).href,
  ammo_multi_shot: new URL(
    "./items/ammo/runtime/ammo_multi_shot.webp",
    import.meta.url,
  ).href,
  ammo_piercing: new URL(
    "./items/ammo/runtime/ammo_piercing.webp",
    import.meta.url,
  ).href,
  trinket_ammo_expander: new URL(
    "./items/trinkets/runtime/trinket_ammo_expander.webp",
    import.meta.url,
  ).href,
  trinket_med_service_module: new URL(
    "./items/trinkets/runtime/trinket_med_service_module.webp",
    import.meta.url,
  ).href,
  trinket_overclock_chip: new URL(
    "./items/trinkets/runtime/trinket_overclock_chip.webp",
    import.meta.url,
  ).href,
  trinket_salvage_module: new URL(
    "./items/trinkets/runtime/trinket_salvage_module.webp",
    import.meta.url,
  ).href,
  trinket_shield_capacitor: new URL(
    "./items/trinkets/runtime/trinket_shield_capacitor.webp",
    import.meta.url,
  ).href,
  trinket_targeting_module: new URL(
    "./items/trinkets/runtime/trinket_targeting_module.webp",
    import.meta.url,
  ).href,
  trinket_thruster_coupler: new URL(
    "./items/trinkets/runtime/trinket_thruster_coupler.webp",
    import.meta.url,
  ).href,
  med_gel: new URL("./items/healing_loot/runtime/med_gel.webp", import.meta.url)
    .href,
  med_kit: new URL("./items/healing_loot/runtime/med_kit.webp", import.meta.url)
    .href,
  salvage_bundle: new URL(
    "./items/healing_loot/runtime/salvage_bundle.webp",
    import.meta.url,
  ).href,
  supply_cache_closed: new URL(
    "./items/healing_loot/runtime/supply_cache_closed.webp",
    import.meta.url,
  ).href,
  supply_cache_open: new URL(
    "./items/healing_loot/runtime/supply_cache_open.webp",
    import.meta.url,
  ).href,
} as const;
