// Generated by scripts/prepare-game-assets.mjs.
export const uiAssets = {
  ui_answer_field: new URL("./ui/runtime/ui_answer_field.webp", import.meta.url)
    .href,
  ui_button_icon: new URL("./ui/runtime/ui_button_icon.webp", import.meta.url)
    .href,
  ui_button_primary: new URL(
    "./ui/runtime/ui_button_primary.webp",
    import.meta.url,
  ).href,
  ui_button_secondary: new URL(
    "./ui/runtime/ui_button_secondary.webp",
    import.meta.url,
  ).href,
  ui_console_panel: new URL(
    "./ui/runtime/ui_console_panel.webp",
    import.meta.url,
  ).href,
  ui_defeat_badge: new URL("./ui/runtime/ui_defeat_badge.webp", import.meta.url)
    .href,
  ui_hud_bar: new URL("./ui/runtime/ui_hud_bar.webp", import.meta.url).href,
  ui_inset_panel: new URL("./ui/runtime/ui_inset_panel.webp", import.meta.url)
    .href,
  ui_item_slot: new URL("./ui/runtime/ui_item_slot.webp", import.meta.url).href,
  ui_joystick_base: new URL(
    "./ui/runtime/ui_joystick_base.webp",
    import.meta.url,
  ).href,
  ui_joystick_knob: new URL(
    "./ui/runtime/ui_joystick_knob.webp",
    import.meta.url,
  ).href,
  ui_legendary_crest: new URL(
    "./ui/runtime/ui_legendary_crest.webp",
    import.meta.url,
  ).href,
  ui_reward_card: new URL("./ui/runtime/ui_reward_card.webp", import.meta.url)
    .href,
  ui_victory_badge: new URL(
    "./ui/runtime/ui_victory_badge.webp",
    import.meta.url,
  ).href,
} as const;
